class UserAlreadyExistsError(Exception):
    """Exceção lançada quando o usuário ou e-mail já existe."""
    pass
